### ISSUE TITLE
script fails on ubuntu 2204 - SOLVED

### ISSUE THREAD

**Issue by taudas** [beltoforion/kalstar#1]
i tried kalstar on ubuntu 2204 which has stellarium 0.20.4.-3. script fails with error ->
"script error: \"TypeError: Result of expression 'core.setMilkyWayVisible' [undefined] is not a function.\" @ line /home/taudas/.stellarium/scripts/kalstar.ssc:49"

deleting that line and the next fixes it.

181a182,183
>     core.setMilkyWayVisible(true);
>     core.setMilkyWayIntensity(4);

**Comment by beltoforion** [comment]
Thanks for reporting this. There was a change in the Stellarium API and the two functions in question are now somewhere else. I have updated the archive.
