### ISSUE TITLE
stargaze in full sky (without ground or landscape)

### ISSUE THREAD

**Issue by sugizo** [beltoforion/kalstar#12]
**objective** 
stargaze in full sky (without ground or landscape)

**add in kalstar.py**
LandscapeMgr.setFlagLandscape(false);

**result work in earth** 
`core.setObserverLocation(long, lat, 425, 1, "Freiberg", "Earth");`

not work in other planets (no error occurs but the result is not expected because still can see the ground)
`core.setObserverLocation(long, lat, 425, 1, "", "Mars");`

already try to debug with set gui visible, 
`core.setGuiVisible(true);`
so that we can click to turn the ground on / off 
**result**
work while stargaze from Mars in full sky

**question**
is there something must be set/configure 
when stargaze outside the earth without see the ground 
?

best regards

**Comment by beltoforion** [comment]
You really need to look into the Stellarium script documentation:
https://stellarium.org/doc/0.20/scripting.html

You are probably looking for this command:
LandscapeMgr.setCurrentLandscapeName("Mars",0);
