### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by fzs1933** [beltoforion/kalstar#15]
Hi,
Kalstar would be - I think - a perfect application for my purpose. But I am not a programmer and just try to find out what the problem is.
Stellarium installed on the drive "E". The scripts directory is E:\Stellarium\scripts.
When I run kalstar.py I get an error: FileNotFoundError: [WinError 3] The system cannot find the available path (or something like this - 'cause my system langauge is Hungarian)  'C:\\Users\\Csillagászkodj!/.stellarium/scripts' 
What I have to modificate in the kalstar.py to works it correct?

Regards
Zsolt

**Comment by beltoforion** [comment]
Could you solve the issue? I'm currently rewriting the script to allow the creation of analemmas and possibly create animations for planets other than earth. I may be able to address this issue i just did not get to it.

**Comment by fzs1933** [comment]
Thanks your answer. I solved it. I made a mistake and wrote earlier than I was thinking.
Kalstar works perfectly. I don't need the sunset calculations, because Stellarium sets the skyview according to the set date, but all the other parts of the program are extremely useful to me.
Indeed I wrote a python program to make a GUI so that you don't have to type a lot of data into the command line.
Thanks again!
Zsolt

**Comment by beltoforion** [comment]
Ok, thanks for the update

**Comment by beltoforion** [comment]
Just fyi; I just pushed an update that can run on windows. The new version can be used to run simulations on other planets as well and the sunset computation was replaced with the skyfield package which is more robust.

**Comment by fzs1933** [comment]
Thanks,
but stay tuned because my python based GUI doesn't give the date to the Stellarium. Can I post the code and if you have a chance, would you take a look? As I go home, will share it.

**Comment by beltoforion** [comment]
If you share it i can have a look at it.

**Comment by fzs1933** [comment]
OK but I run a test with the stellarium-to-video.py
if I can't understand or apply it, I'll let you know
it can be a few days

**Comment by fzs1933** [comment]
Hi, i run the new program and got this message:

←[93mWarning: No time given. The script will try to use the sunset time of the given day!←[0m
Traceback (most recent call last):
  File "C:\Stellarium\scripts\stellarium-to-video.py", line 341, in <module>
    main()
  File "C:\Stellarium\scripts\stellarium-to-video.py", line 326, in main
    raise Exception('Stellarium does not seem to be installed!')
Exception: Stellarium does not seem to be installed!

is it possible that the directory is read-only?

**Comment by fzs1933** [comment]
F...in' win10 - i cant remove write protection from directories

**Comment by fzs1933** [comment]
So, as I saw, Stellarium folder wasnt it in AppData/Roaming. I created it. But have a new error... :)
I copied default.ssc to the Scripts folder.

←[93mWarning: No time given. The script will try to use the sunset time of the given day!←[0m
Traceback (most recent call last):
  File "E:\Stellarium\scripts\stellarium-to-video.py", line 341, in <module>
    main()
  File "E:\Stellarium\scripts\stellarium-to-video.py", line 334, in main
    sa.create_script(script_folder)
  File "E:\Stellarium\scripts\stellarium-to-video.py", line 160, in create_script
    with open(f'./script/{self.__param.template}', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './script/default.ssc'

Apologize me for my problems!
I keep trying.

**Comment by fzs1933** [comment]
I use hungarian version of windows and chose an idiot user name: Csillagászkodj!
(I dont understand "right click, open terminal)


C:\Users\Csillagászkodj!\Downloads\stellarium-to-video-master>pip install -r requirements.txt
Fatal error in launcher: Unable to create process using '"C:\Users\Csillagßszkodj!\AppData\Local\Programs\Python\Python312\python.exe"  "C:\Users\Csillagßszkodj!\AppData\Local\Programs\Python\Python312\Scripts\pip.exe" install -r requirements.txt': A rendszer nem talßlja a megadott fßjlt.

![path](https://github.com/beltoforion/stellarium-to-video/assets/81897104/e8fa77c5-b191-4097-b3e6-86a553bb1baf)

**Comment by fzs1933** [comment]
Reinstall python solved a lot of problems. 
stellarium-to-video.py run
i test it for a few days - for my purposes and will brief
thanks a lot of your help!

**Comment by beltoforion** [comment]
Thats great!

**Comment by fzs1933** [comment]
Excuse me, I am trying parallel: at home and workplace.
Py program runs well at home, but at workplace always drops this message:
**Checking prerequisites:
  - Stellarium found at "E:\Stellarium\stellarium.EXE"
  - ffmpeg found at "C:\Program Files (x86)\ffmpeg\bin\ffmpeg.EXE"
  - Vlc found at "C:\Program Files (x86)\VideoLAN\VLC\vlc.EXE"
Location:
  - lon=13.3428889, lat=50.9169415, address="Freiberg, Mittelsachsen, Sachsen, 09599, Deutschland"
  - planet="Earth"
  - template="suntrack.ssc"
Time:
  - start=2024-06-20T12:00:00+01:00, timespan=31557600.0 s, delta_t=172800.0 s
View:
  - alt=35.0°, az=180.0°, fov=70.0°
Video:
  - caption="Analemma"
  - file="analemma.mp4"

←[91mError: Stellarium does not seem to be installed!←[0m**
Stellarium is installed drive E:\stellarium. I refresh py file (is it possible that something escaped my attention) and PATH
I attach the refreshed py.
I'll get to it, it's not urgent!
[stellarium-to-video.txt](https://github.com/beltoforion/stellarium-to-video/files/14383191/stellarium-to-video.txt)

**Comment by beltoforion** [comment]
I checked the last script version. It still contained two hardcoded references to stellarium being installed on drive c. I removed those. With the latest version you should now be able to execute the script even though stellarium is installed on drive e provided you have added the stellarium folder to the search path. If you don't the script should tell you at startup with an error message.
