### ISSUE TITLE
Wraparound Sun Calculation

### ISSUE THREAD

**Issue by jmadajian** [beltoforion/kalstar#3]
With certain negative longitude values, I received the error 

`AttributeError: 'sun' object has no attribute 'sunset_t'. Did you mean: 'sunset'?`

This can be fixed by allowing for the sunrise and sunset times to wrap around:

       self.sunrise_t = self.solarnoon_t - hourangle * 4 / 1440
        if self.sunrise_t > 1:
            sunrise_t -= 1
        elif self.sunrise_t < 0:
            sunrise_t += 1

        self.sunset_t = self.solarnoon_t + hourangle * 4 / 1440
        if self.sunset_t > 1:
            self.sunset_t -= 1
        elif self.sunset_t < 0:
            sunset_t += 1

**Comment by beltoforion** [comment]
Can you give me an example which values would create this error?

**Comment by beltoforion** [comment]
Ok, i can see it now. Thanks for the fix!
