### ISSUE TITLE
core.setGuiVisible(false); not work

### ISSUE THREAD

**Issue by sugizo** [beltoforion/kalstar#5]
**code**
`core.setGuiVisible(false);`

not work, because gui still visible or open during processing

as in the config still set true, even try to edit manually with vim

`cat ~/.stellarium/scripts/kalstar.ssc`

**exptected result** 
headless or no gui during processing

best regards

**Comment by beltoforion** [comment]
This is not reproducible. It may be an issue with Stellarium itself or the specific version of stellarium.

**Comment by sugizo** [comment]
**code from github**
```
a@T85P8A3:~$ cat kalstar/kalstar.py | grep Gui
    core.setGuiVisible(false);
    core.setGuiVisible(true);
a@T85P8A3:~$ cat .stellarium/scripts/kalstar.ssc | grep Gui
    core.setGuiVisible(false);
    core.setGuiVisible(true);
a@T85P8A3:~$ stellarium -v
Stellarium 0.20.4
```

even try to set manually core.setGuiVisible(false); from both files kalstar.py and kalstar.ssc, 
the result is Gui still opened

**environment**
ubuntu jammy

**Comment by beltoforion** [comment]
I'm running stellarium 0.20.4 on linux. I cannot reproduce the issue. The controls are not shown on my system as would be expected by issuing this command. But of course the stellarium window will always pop up. This command will only hide the control bar inside the stellarium window and for all i can say it is working. It cannot hide the main window if this is what you are aiming for. 

 There is nothing i can do. This is a Stellarium command. What it does and does not do is outside of my control.
