### ISSUE TITLE
the simulation date paramter (-d) always execute day + 1

### ISSUE THREAD

**Issue by sugizo** [beltoforion/kalstar#8]
**objective**
see the sky on the night of new year 

**execute on terminal**
```
python3 kalstar.py -t "Paris, France" -lat 48.8566 -long 2.3522 -d 2020-01-01 -az 90 -alt 25 -fov 70 \
-fps 30 -ts 1 -dt 30 -o out.mp4
```

**will result**
2020-01-02

**expected result**
2020-01-01

**question**
is it normal or should i use the backdate as parameter e.g. 2019-12-31 ?

best regards

**Comment by beltoforion** [comment]
That is not normal but i cannot reproduce the issue with Stellarium 0.20.4 . Is this only happening with Stellarium 23.x?

**Comment by beltoforion** [comment]
Closed; Not reproducible
