### ISSUE TITLE
run on mac success but need some modification in executable path

### ISSUE THREAD

**Issue by sugizo** [beltoforion/kalstar#9]
**ffmpeg**
```
cd ~/Downloads
curl -LOC - https://evermeet.cx/ffmpeg/ffmpeg-6.0.zip
unzip ffmpeg-*.zip
```

**stellarium**
```
cd ~/Downloads
curl -LOC - https://github.com/Stellarium/stellarium/releases/download/v23.3/Stellarium-23.3-qt6-macOS.zip
unzip Stellarium-*.zip
mv Stellarium.app /Applications/
open /Applications/Stellarium.app
```

**kalstar**
```
cd ~/Downloads
git clone https://github.com/beltoforion/kalstar
mkdir -p ~/.stellarium/scripts
```

**edit kalstar.py for the path apps**
```
        proc_stellarium = subprocess.Popen(['/Applications/Stellarium.app/Contents/MacOS/stellarium', '--startup-script', '/Users/your_mac_user/.stellarium/scripts/kalstar.ssc', '--screenshot-dir', self.__frame_folder], stdout=subprocess.PIPE);

        proc = subprocess.Popen(['/Users/your_mac_user/Downloads/ffmpeg',
```

**run app**
```
cd ~/Downloads
python3 kalstar/kalstar.py -t "Paris, France" -lat 48.8566 -long 2.3522 -d 2020-01-01 -az 90 -alt 25 -fov 70 \
-fps 30 -ts 1 -dt 30 -o ~/Downloads/out.mp4
```

**suggestion**
- for different os perhaps need some parameter for executable app, 
e.g. 
kalstar.py -stelarium_path /bin/stellarium -ffmpeg_path /bin/ffmpeg
or
- make another files, 
e.g. 
kalstar_ubuntu.py, kalstar_mac.py, kalstar_windows.py

**note**
already report about user must create directory manually ~/.stellarium/scripts,
but still not fixed tested on both ubuntu n mac

best regards

**Comment by beltoforion** [comment]
Unfortunately I cannot support Mac's. I'm willing to merge any PR addressing this issue provided it does not break the script on other systems. But personally I don't have a mac and i'm not inclined to invest time into supporting something i don't use and cannot test.

**Comment by sugizo** [comment]
same file (kalstar.py just different the executable path for mac n linux) 
same argument 
python3 /mnt/c/kalstar_linux.py \
-t "Nairobi, Kenya" -lat -1.2921 -long 36.8219 -d 1948-12-22 -az 90 -alt 25 -fov 70 \
-fps 10 -ts 2 -dt 10 -o /mnt/c/out.mp4

python3 ~/Downloads/kalstar_mac.py \
-t "Nairobi, Kenya" -lat -1.2921 -long 36.8219 -d 1948-12-22 -az 90 -alt 25 -fov 70 \
-fps 10 -ts 2 -dt 10 -o ~/Downloads/out.mp4

different (os and apps version, 
ubuntu use stellarium 0.20.4, mac 23.3, 
ubuntu use ffmpeg 5, mac version 6

have different result in time
in ubuntu the video duration 1:12
while in mac < 1 minute

not sure, the problem in ffmpeg different version 
or
stellarium different version
or
in os 

the result generated with ubuntu uploaded on my youtube channel
https://www.youtube.com/watch?v=18_wm9s8ZFk&list=PLQLwDsJdI4wtGMMLhUfe2o4kL26V4Rk2_

**Comment by beltoforion** [comment]
closed; Its pretty obvious that if the script creates different results with different Stellarium versions the reason for the behavior is probably a change in Stellarium. This is outside of the scope of this script.
